name: housing_flutter_app
description: "A Flutter housing application with authentication and API integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  http:
  flutter_secure_storage:
  cached_network_image:
  shimmer:
  carousel_slider:
  intl:
  image_picker:
  get:
  connectivity_plus:
  internet_connection_checker_plus:
  awesome_snackbar_content:
  salomon_bottom_bar:
  font_awesome_flutter:
  flutter_svg:
  google_fonts:
  smooth_page_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/icons/comments/
    - assets/icons/employee/
    - assets/icons/functions/
    - assets/icons/member/
    - assets/icons/native_icons/
    - assets/icons/native_icons/actions/
    - assets/icons/native_icons/auth/
    - assets/icons/native_icons/business/
    - assets/icons/native_icons/date_time/
    - assets/icons/native_icons/file/
    - assets/icons/native_icons/media/
    - assets/icons/native_icons/navigation/
    - assets/icons/native_icons/navigation/arrow/
    - assets/icons/native_icons/notification/
    - assets/icons/native_icons/system/
    - assets/icons/native_icons/ui/
    #- .env

  # Comment out fonts until they are available
  fonts:
    - family: NuNunito_Sans
      fonts:
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-ExtraLight.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-Light.ttf
          weight: 300
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NuNunito_Sans/NunitoSans_10pt-Black.ttf
          weight: 900

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800




