import 'package:flutter/material.dart';
import 'package:housing_flutter_app/app/constants/color_res.dart';

List<Map<String, dynamic>> propertyList = [
  {
    "id": 1,
    "title": "Luxury Apartment in City Center",
    "type": "Apartment",
    "price": 8500000.00,
    "percentage_increase": "13.4",
    "price_per_sqft": (8500000 / 1450).toStringAsFixed(2),
    "area_sqft": 1450,
    "builder": "ABC Builders",
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "price_range": {"min": "80 Lakh", "max": "90 Lakh"},
    "currency": "INR",
    "status": "For Sale",
    "bedrooms": 3,
    "bathrooms": 2,
    "address": {
      "street": "MG Road",
      "city": "Mumbai",
      "state": "Maharashtra",
      "pincode": "400001",
    },

    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],

    "complete_address": "MG Road, Mumbai, Maharashtra, 400001",
    "amenities": ["Gym", "Swimming Pool", "Parking", "24x7 Security"],
    "image":
        "assets/image/modern-residential-buildings-with-wooden-facades.jpg",
    "owner": {
      "name": "Rohit Sharma",
      "contact": "+91-9876543210",
      "email": "rohit@example.com",
    },
    "seller": {
      "name": "Ravi Sharma",
      "experience": 12,
      "location": "Mumbai",
      "properties_count": 25,
      "total_active_properties": 20,
      "buy": 12,
      "rent": 5,
      "commercial_buy": 2,
      "commercial_rent": 1,
      "proprietorship": "Individual",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["South Mumbai", "Bandra", "Andheri"],
      "image": "assets/profile/profile.png",
    },
    "rating": 4.5,

    // ✅ New Analytics
    "appreciation_1yr": 12.8,
    "avg_rate_per_sqft": 6100,
    "transactions_1yr": 36,

    "price_trend": [
      {"year": 2020, "price": 6800000},
      {"year": 2021, "price": 7200000},
      {"year": 2022, "price": 7800000},
      {"year": 2023, "price": 8200000},
      {"year": 2024, "price": 8500000},
    ],
  },
  {
    "id": 2,
    "title": "2 BHK Flat near Railway Station",
    "type": "Flat",
    "percentage_increase": "3.9",
    "price": 22000,
    "price_per_sqft": (22000 / 950).toStringAsFixed(2),
    "area_sqft": 950,
    "price_range": {"min": "54.20 Lakh", "max": "60.1 Lakh"},
    "currency": "INR",

    "status": "For Rent",
    "builder": "ABC Builders",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "bedrooms": 2,
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "bathrooms": 1,
    "address": {
      "street": "Station Road",
      "city": "Delhi",
      "state": "Delhi",
      "pincode": "110001",
    },
    "complete_address": "Station Road, Delhi, 110001",
    "amenities": ["Lift", "Parking", "CCTV"],
    "image": "assets/image/urban-traffic-with-cityscape.jpg",
    "owner": {
      "name": "Neha Verma",
      "contact": "+91-9988776655",
      "email": "neha@example.com",
    },
    "seller": {
      "name": "Neha Kapoor",
      "experience": 8,
      "location": "Delhi",
      "properties_count": 18,
      "total_active_properties": 14,
      "buy": 7,
      "rent": 4,
      "commercial_buy": 2,
      "commercial_rent": 1,
      "proprietorship": "Individual",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Connaught Place", "Gurgaon", "Noida"],
      "image": "assets/profile/profile1.png",
    },
    "rating": 4.0,

    // ✅ New Analytics
    "appreciation_1yr": 4.2,
    "avg_rate_per_sqft": 5750,
    "transactions_1yr": 22,

    "price_trend": [
      {"year": 2020, "price": 18000},
      {"year": 2021, "price": 19000},
      {"year": 2022, "price": 20000},
      {"year": 2023, "price": 21000},
      {"year": 2024, "price": 22000},
    ],
  },
  {
    "id": 3,
    "title": "Independent Villa with Garden",
    "type": "Villa",
    "price": 16500000,
    "price_per_sqft": (16500000 / 2800).toStringAsFixed(2),
    "area_sqft": 2800,
    "percentage_increase": "2.5",
    "price_range": {"min": "2.5 Cr", "max": "6.1 Cr"},
    "currency": "INR",
    "status": "For Sale",
    "builder": "ABC Builders",
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "bedrooms": 4,
    "bathrooms": 3,
    "address": {
      "street": "Palm Meadows",
      "city": "Pune",
      "state": "Maharashtra",
      "pincode": "411001",
    },
    "complete_address": "Palm Meadows, Pune, Maharashtra, 411001",
    "amenities": ["Private Garden", "Car Parking", "Modular Kitchen"],
    "image": "assets/image/vertical-shot-modern-apartments-daytime.jpg",
    "owner": {
      "name": "Arjun Kapoor",
      "contact": "+91-9090909090",
      "email": "arjun@example.com",
    },
    "seller": {
      "name": "Amit Real Estates",
      "experience": 15,
      "location": "Pune",
      "properties_count": 40,
      "total_active_properties": 32,
      "buy": 20,
      "rent": 6,
      "commercial_buy": 4,
      "commercial_rent": 2,
      "proprietorship": "Company",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Koregaon Park", "Hinjewadi", "Kalyani Nagar"],
      "image": "assets/profile/profile2.png",
    },
    "rating": 4.8,

    // ✅ New Analytics
    "appreciation_1yr": 6.5,
    "avg_rate_per_sqft": 5900,
    "transactions_1yr": 28,

    "price_trend": [
      {"year": 2020, "price": 14000000},
      {"year": 2021, "price": 14800000},
      {"year": 2022, "price": 15500000},
      {"year": 2023, "price": 16000000},
      {"year": 2024, "price": 16500000},
    ],
  },
  {
    "id": 4,
    "title": "Commercial Office Space",
    "type": "Office",
    "price": 75000,
    "percentage_increase": "17.13",
    "price_per_sqft": (75000 / 1200).toStringAsFixed(2),
    "area_sqft": 1200,
    "price_range": {"min": "25.20 Lakh", "max": "27.1 Lakh"},
    "currency": "INR",
    "builder": "Dream Homes Pvt Ltd",
    "establish_year": 1995,
    "projects_count": 12,
    "logo": "assets/logo/Avant.jpg",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "status": "For Rent",
    "bedrooms": 0,
    "bathrooms": 2,
    "address": {
      "street": "Cyber City",
      "city": "Bangalore",
      "state": "Karnataka",
      "pincode": "560001",
    },
    "complete_address": "Cyber City, Bangalore, Karnataka, 560001",
    "amenities": ["Power Backup", "Lift", "Conference Room"],
    "image":
        "assets/image/modern-residential-buildings-with-wooden-facades.jpg",
    "owner": {
      "name": "Shweta Singh",
      "contact": "+91-9123456789",
      "email": "shweta@example.com",
    },
    "seller": {
      "name": "Sunrise Properties",
      "experience": 10,
      "location": "Bangalore",
      "properties_count": 30,
      "total_active_properties": 24,
      "buy": 12,
      "rent": 6,
      "commercial_buy": 3,
      "commercial_rent": 3,
      "proprietorship": "Company",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Whitefield", "Electronic City", "Indiranagar"],
      "image": "assets/profile/profile3.png",
    },
    "rating": 3.9,

    // ✅ New Analytics
    "appreciation_1yr": 10.2,
    "avg_rate_per_sqft": 5000,
    "transactions_1yr": 19,

    "price_trend": [
      {"year": 2020, "price": 60000},
      {"year": 2021, "price": 63000},
      {"year": 2022, "price": 67000},
      {"year": 2023, "price": 71000},
      {"year": 2024, "price": 75000},
    ],
  },
  {
    "id": 5,
    "title": "Luxury Villa on ECR Road",
    "type": "Villa",
    "price": 9800000,
    "percentage_increase": "6.13",
    "price_per_sqft": (9800000 / 1800).toStringAsFixed(2),
    "area_sqft": 1800,
    "price_range": {"min": "90 Lakh", "max": "1.1 Cr"},
    "currency": "INR",
    "builder": "Dream Homes Pvt Ltd",
    "good_things": [
      "Clean and well-maintained property",
      "Safe and secure location",
      "Friendly and responsive owner/agent",
      "Easy and smooth booking process",
      "Affordable pricing compared to market",
      "Modern amenities (Wi-Fi, parking, appliances, etc.)",
      "Comfortable interiors and good furniture",
      "Good neighborhood and accessibility (shops, transport, schools)",
      "Accurate property photos and descriptions",
      "Quick issue resolution / good customer support",
    ],
    "needs_improvement": [
      "Property not clean or poorly maintained",
      "Noisy or unsafe neighborhood",
      "Unresponsive owner/agent",
      "Complicated booking or payment process",
      "High pricing for value offered",
      "Missing or broken amenities",
      "Poor interior condition (furniture, walls, appliances)",
      "Inconvenient location or lack of accessibility",
      "Misleading property photos/descriptions",
      "Delayed issue resolution / poor support",
    ],
    "status": "For Sale",
    "establish_year": 2010,
    "projects_count": 4,
    "logo": "assets/logo/Avant.jpg",
    "bedrooms": 3,
    "bathrooms": 3,
    "address": {
      "street": "ECR Road",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "pincode": "600041",
    },
    "complete_address": "ECR Road, Chennai, Tamil Nadu, 600041",
    "amenities": ["Sea View", "Car Parking", "Security"],
    "image": "assets/image/vertical-shot-modern-apartments-daytime.jpg",
    "owner": {
      "name": "Karthik Iyer",
      "contact": "+91-7777777777",
      "email": "karthik@example.com",
    },
    "seller": {
      "name": "Karan Verma",
      "experience": 6,
      "location": "Chennai",
      "properties_count": 12,
      "total_active_properties": 9,
      "buy": 4,
      "rent": 3,
      "commercial_buy": 1,
      "commercial_rent": 1,
      "proprietorship": "Individual",
      "description":
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      "area_of_operation": ["Anna Nagar", "T Nagar", "OMR"],
      "image": "assets/profile/profile4.png",
    },
    "rating": 4.6,

    // ✅ New Analytics
    "appreciation_1yr": 8.7,
    "avg_rate_per_sqft": 5450,
    "transactions_1yr": 25,

    "price_trend": [
      {"year": 2020, "price": 8500000},
      {"year": 2021, "price": 8800000},
      {"year": 2022, "price": 9100000},
      {"year": 2023, "price": 9500000},
      {"year": 2024, "price": 9800000},
    ],
  },
];

List builderList = [
  {
    "title": "ABC Builders",
    "establish_year": 1995,
    "projects_count": 12,
    "image": "assets/logo/Avant.jpg",
  },
  {
    "title": "XYZ Constructions",
    "establish_year": 2002,
    "projects_count": 7,
    "image": "assets/logo/professional.jpg",
  },
  {
    "title": "Dream Homes Pvt Ltd",
    "establish_year": 2010,
    "projects_count": 4,
    "image": "assets/logo/xYZ.jpg",
  },
];

final stats = [
  {
    "title": "Appreciation",
    "value": "${propertyList[0]['appreciation_1yr']}%",
    "subText": "(1 Year)",
    "icon": Icons.arrow_upward,
    "iconColor": ColorRes.success,
  },
  {
    "title": "Avg. rate",
    "value": "₹ ${propertyList[0]['price_per_sqft']} / sqft",
    "subText": null,
    "icon": null,
  },
  {
    "title": "Transaction",
    "value": "${propertyList[0]['transactions_1yr']}",
    "subText": "(1 Year)",
    "icon": null,
  },
  {
    "title": "Price Range",
    "value":
        "₹ ${propertyList[0]['price_range']['min']} - ₹ ${propertyList[0]['price_range']['max']}",
    "subText": null,
    "icon": null,
  },
];

List<String> propertyType = ['Buy', 'Rent', 'Commercial', 'PG/Co-living'];

List<String> bHkType = [
  "All",
  "1 Rk",
  "1 BHK",
  "2 BHK",
  "3 BHK",
  "4 BHK",
  "5 BHK",
  "5+ BHK",
];

List<String> propertyTypesList = [
  "All",
  "Apartments",
  "Independent House",
  "Plot",
  "Studio",
  "Duplex",
  "PentHouse",
  "Builder Floor",
  "Villa",
];

List<String> listedByList = [
  "All",
  "Agent",
  "Owner",
  "Builder",
  "Expert Pro Agent",
];

List<String> constructionStatus = [
  'All',
  'Ready to move',
  "Under Construction",
  "New Launch",
];

List<String> furnishingType = [
  "All",
  "Unfurnished",
  "Semi Furnished",
  "Fully Furnished",
];
List<String> subCategory = ['Buy', 'Lease'];

List<String> buyCommercialPropertyType = [
  "Ready to use Office Space",
  "Bare Shell Office Space",
  "Shop",
  "Showroom",
  "Commercial Plot",
  "WareHouse",
  "Others",
];
List<String> saleTypeCommercialProperty = [
  "New Properties",
  "Resale Properties",
];

List<String> leaseTypeCommercialProperty = ['Pre-Leased', 'Non-Leased'];
List<String> possessionCommercialList = ["Ready to move", "Under Construction"];

List<String> genderList = ['Male', 'Female', 'Both'];
List<String> roomTypeList = [
  "Private Room",
  "Double Sharing",
  "Triple Sharing",
  "3+ Sharing",
];
List<String> foodAvailable = ['Yes', 'No'];

List<String> localityList = [
  'Andheri West',
  'Andheri',
  'Surat',
  'Mumbai',
  'Patna',
];
final Map<String, List<String>> popularCitiesWithAreas = {
  'Mumbai': [
    'Bandra',
    'Andheri',
    'Juhu',
    'Powai',
    'Borivali',
    'Colaba',
    'Andheri',
    'Juhu',
    'Powai',
    'Borivali',
    'Colaba',
  ],
  'Delhi': [
    'Connaught Place',
    'Saket',
    'Hauz Khas',
    'Karol Bagh',
    'Dwarka',
    'Vasant Kunj',
  ],
  'Bengaluru': [
    'Whitefield',
    'Indiranagar',
    'Koramangala',
    'Jayanagar',
    'MG Road',
    'Electronic City',
  ],
  'Hyderabad': [
    'Banjara Hills',
    'Jubilee Hills',
    'Gachibowli',
    'Madhapur',
    'Begumpet',
    'Hitech City',
  ],
  'Ahmedabad': [
    'Satellite',
    'Vastrapur',
    'Navrangpura',
    'Bodakdev',
    'CG Road',
    'Maninagar',
  ],
  'Chennai': [
    'T. Nagar',
    'Anna Nagar',
    'Velachery',
    'Adyar',
    'Nungambakkam',
    'Tambaram',
  ],
  'Kolkata': [
    'Salt Lake',
    'Park Street',
    'Ballygunge',
    'Howrah',
    'Dum Dum',
    'New Town',
  ],
  'Pune': [
    'Koregaon Park',
    'Viman Nagar',
    'Kothrud',
    'Baner',
    'Hinjewadi',
    'Magarpatta',
  ],
  'Surat': [
    'Adajan',
    'Vesu',
    'City Light',
    'Athwalines',
    'Varachha',
    'Nanpura',
  ],
  'Jaipur': [
    'Malviya Nagar',
    'Vaishali Nagar',
    'Mansarovar',
    'C-Scheme',
    'Raja Park',
    'Tonk Road',
  ],
  'Lucknow': [
    'Hazratganj',
    'Gomti Nagar',
    'Indira Nagar',
    'Alambagh',
    'Charbagh',
    'Aminabad',
  ],
  'Indore': [
    'Vijay Nagar',
    'Rajwada',
    'Palasia',
    'Bhawarkuan',
    'MR 10 Road',
    'Rau',
  ],
  'Bhopal': [
    'Arera Colony',
    'MP Nagar',
    'Kolar Road',
    'Shahpura',
    'New Market',
    'BHEL Township',
  ],
  'Nagpur': [
    'Dharampeth',
    'Sitabuldi',
    'Civil Lines',
    'Manish Nagar',
    'Pratap Nagar',
    'Sadar',
  ],
  'Vadodara': [
    'Alkapuri',
    'Gotri',
    'Manjalpur',
    'Sayajigunj',
    'Fatehgunj',
    'Akota',
  ],
};

String popularCities = 'Mumbai';

Map<String, List<String>> letterAlphabate = {
  "A": ["Agra", "Ajmer", "Ahmedabad", "Aligarh", "Aurangabad"],
  "B": ["Bhopal", "Bhubaneswar", "Bangalore", "Bareilly", "Bilaspur"],
  "C": ["Chennai", "Chandigarh", "Coimbatore", "Cuttack", "Chittoor"],
  "D": ["Delhi", "Dehradun", "Darjeeling", "Dhanbad", "Durgapur"],
  "E": ["Ernakulam", "Eluru", "Etawah", "Erode", "East Champaran"],
  "F": ["Faridabad", "Firozabad", "Faizabad", "Fatehpur", "Fazilka"],
  "G": ["Goa", "Guwahati", "Gandhinagar", "Gwalior", "Gorakhpur"],
  "H": ["Hyderabad", "Haridwar", "Haldwani", "Hazaribagh", "Hisar"],
  "I": ["Indore", "Imphal", "Itanagar", "Ichalkaranji", "Idar"],
  "J": ["Jaipur", "Jodhpur", "Jamshedpur", "Jhansi", "Jalandhar"],
  "K": ["Kolkata", "Kanpur", "Kochi", "Kota", "Kozhikode"],
  "L": ["Lucknow", "Ludhiana", "Leh", "Latur", "Lakshadweep"],
  "M": ["Mumbai", "Mysore", "Meerut", "Mangalore", "Moradabad"],
  "N": ["Nagpur", "Noida", "Nashik", "Nellore", "Nainital"],
  "O": ["Ooty", "Osmanabad", "Ori", "Ongole", "Ottapalam"],
  "P": ["Pune", "Patna", "Panaji", "Pondicherry", "Prayagraj"],
  "Q": ["Quilon", "Qadian", "Quepem", "Quarry Hill", "Qazigund"],
  "R": ["Ranchi", "Rajkot", "Rishikesh", "Rewa", "Rohtak"],
  "S": ["Surat", "Srinagar", "Shimla", "Silchar", "Salem"],
  "T": ["Thane", "Tirupati", "Trivandrum", "Tinsukia", "Tezpur"],
  "U": ["Udaipur", "Ujjain", "Unnao", "Una", "Udhampur"],
  "V": ["Varanasi", "Vijayawada", "Visakhapatnam", "Valsad", "Vadodara"],
  "W": ["Warangal", "Wardha", "Wokha", "Washim", "Wayanad"],
  "X": ["Xeldem", "Xankandi", "Xoxombel", "Xirivella", "Xomokul"],
  "Y": ["Yamunanagar", "Yavatmal", "Yanam", "Yelagiri", "Yeola"],
  "Z": ["Zirakpur", "Zunheboto", "Ziro", "Zamania", "Zaidpur"],
};
